# Site settings
baseurl = "https://cgk.sh/"
languageCode = "en-us"
title = "Colby GK"
theme = "hugo-xmag"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"
hasCJKLanguage = true
enableEmoji = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    github_edit = "https://github.com/yihui/hugo-xmag/edit/master/exampleSite/content/"
    footer = "&copy; [Colby GK](https://cgk.sh) 2017 | [Github](https://github.com/colbygk) | [Twitter](https://twitter.com/colbygk)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"

