baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Colby GK"
theme = "docdock"

[params]
editURL = "https://github.com/colbygk/cgk.sh/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "simpleflat" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> github"
identifier = "ds"
url = "https://github.com/colbygk"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-flask'></i> projects"
url = "/showcase"
weight = 11

